currency:
  url: ${API_URL:https://api.apilayer.com/fixer/convert}
  #api_key: ${API_KEY:hKOSY55V1VVqszEwTNp8RHfsBpmi9GZg}
  #api_key: ${API_KEY:wocuSTzmZNR00x9jn4NYCef5FMd66NjH}
  api_key: ${API_KEY:PZgoyB7LALgEpDwopDXQyHYeTW14rrK1}
server:
  port: 8080

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter
keycloak:
  realm: Software
  auth-server-url: http://localhost:8081
  ssl-required: external
  resource: backend
#    autodetect-bearer-only: true
  credentials:
    secret: g5Aybp0sCbL3kXeHnoFzv16wdRZq5AXe
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN

      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          methods:
            -GET
          patterns:
            - /api/currency/*
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DE USER
          patterns:
            - /api/currency/*