services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - C:\Users\MSI\pgdata:/var/lib/postgresql/data
    networks:
      - carlos-network
  currency-converter:
    image: demo:2.1.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\MSI\logs-springdk:/Users/MSI/logs-springdk/logs-chapulin
    depends_on:
      - postgres
    networks:
      - carlos-network
  angular:
    image: angular-software:4.0.0-docker
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - carlos-network
networks:
  carlos-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1